/** Stable detail / error codes for the real adapter path (non-stub). */

export const REAL_PROBE_TARGET_NOT_CONFIGURED = "PROBE_TARGET_NOT_CONFIGURED"
export const REAL_PROBE_CONFIG_INVALID = "PROBE_CONFIG_INVALID"
export const REAL_PROBE_TCP_TIMEOUT = "PROBE_TCP_TIMEOUT"
export const REAL_PROBE_TCP_REFUSED = "PROBE_TCP_CONNECTION_REFUSED"
export const REAL_PROBE_TCP_HOST_NOT_FOUND = "PROBE_TCP_HOST_NOT_FOUND"
export const REAL_PROBE_TCP_ERROR = "PROBE_TCP_ERROR"

export const REAL_ASSOCIATION_NOT_IMPLEMENTED = "ASSOCIATION_NOT_IMPLEMENTED"
export const REAL_READ_IDENTITY_NOT_IMPLEMENTED = "READ_IDENTITY_NOT_IMPLEMENTED"
export const REAL_READ_CLOCK_NOT_IMPLEMENTED = "READ_CLOCK_NOT_IMPLEMENTED"
export const REAL_READ_REGISTERS_NOT_IMPLEMENTED = "READ_REGISTERS_NOT_IMPLEMENTED"
export const REAL_RELAY_DISCONNECT_NOT_IMPLEMENTED = "RELAY_DISCONNECT_NOT_IMPLEMENTED"
export const REAL_RELAY_RECONNECT_NOT_IMPLEMENTED = "RELAY_RECONNECT_NOT_IMPLEMENTED"
